project_id = "molmsqlnngtusxeggeij"

[functions.places-search]
verify_jwt = false

[functions.spotify-search]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.check-trial-status]
verify_jwt = false
